title: "Your Name"
description: >- # your site description
  Quant Strategist | Trading Strategies | Financial Modeling
baseurl: "" # the subpath of your site, leave empty
url: "https://sundarganesh21.github.io"
theme: minima
